# see: https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases
# may supplement with a parser function in future projects:
# example functionality:
# p("at the end of every month") -> ['month','end'] -> ['M']
# p('at the start of each quarter') -> p() -> ['start','quarter'] -> ['QS']
# p('monthly and quarterly') -> p() -> ['month','quarter'] -> ['M'] [highest freq. time]

alias_dict = {
'SD': ['start date','one-time','initial','pre-existing'], # this is treated as an exception!
'B': ['business day','work day','weekday'],
'C': ['custom business day'],
'D': ['calendar day','day','daily'],
'W': ['weekly','week'],
'2W': ['biweekly'],
'M': ['month end','month','monthly'],
'SM': ['semi-month end'],
'BM': ['business month end'],
'CBM': ['custom business month end'],
'MS': ['month start'],
'SMS': ['semi-month start'],
'BMS': ['business month start'],
'CBMS': ['custom business month start'],
'Q': ['quarter end','quarter','quarterly'],
'BQ': ['business quarter end'],
'QS': ['quarter start'],
'BQS': ['business quarter start'],
'A': ['year end','y','annual','yearly','annually'],
'BA': ['business year end','by'],
'AS': ['year start','ys'],
'BAS': ['business year start','bys'],
'BH': ['business hour','work hour'],
'H': ['hourly','hour','hr'],
'T': ['minutely','minute','min'],
'S': ['secondly','sec'],
'L': ['milliseconds','ms'],
'U': ['microseconds','us'],
'N': ['nanoseconds'],
'W-SUN': ['sundays','sunday'],
'W-MON': ['mondays','monday'],
'W-TUE': ['tuesdays','tuesday'],
'W-WED': ['wednesdays','wednesday'],
'W-THU': ['thursdays','thursday'],
'W-FRI': ['fridays','friday'],
'W-SAT': ['saturdays','saturday'],
'BQS-DEC': ['quarter december'],
'BQS-JAN': ['quarter january'],
'BQS-FEB': ['quarter february'],
'BQS-MAR': ['quarter march'],
'BQS-APR': ['quarter april'],
'BQS-MAY': ['quarter may'],
'BQS-JUN': ['quarter june'],
'BQS-JUL': ['quarter july'],
'BQS-AUG': ['quarter august'],
'BQS-SEP': ['quarter september'],
'BQS-OCT': ['quarter october'],
'BQS-NOV': ['quarter november'],
'BAS-DEC': ['december'],
'BAS-JAN': ['january'],
'BAS-FEB': ['february'],
'BAS-MAR': ['march'],
'BAS-APR': ['april'],
'BAS-MAY': ['may'],
'BAS-JUN': ['june'],
'BAS-JUL': ['july'],
'BAS-AUG': ['august'],
'BAS-SEP': ['september'],
'BAS-OCT': ['october'],
'BAS-NOV': ['november'],
'A-DEC': ['december end'],
'A-JAN': ['january end'],
'A-FEB': ['february end'],
'A-MAR': ['march end'],
'A-APR': ['april end'],
'A-MAY': ['may end'],
'A-JUN': ['june end'],
'A-JUL': ['july end'],
'A-AUG': ['august end'],
'A-SEP': ['september end'],
'A-OCT': ['october end'],
'A-NOV': ['november end'],
'AS-DEC': ['december start'],
'AS-JAN': ['january start'],
'AS-FEB': ['february start'],
'AS-MAR': ['march start'],
'AS-APR': ['april start'],
'AS-MAY': ['may start'],
'AS-JUN': ['june start'],
'AS-JUL': ['july start'],
'AS-AUG': ['august start'],
'AS-SEP': ['september start'],
'AS-OCT': ['october start'],
'AS-NOV': ['november start'],
}